const CampPageActionTypes = {
  SET_CURRENT_MISSION: "SET_CURRENT_MISSION",
  TOGGLE_MISSION_COMPLETE: "TOGGLE_MISSION_COMPLETE",
  TOGGLE_MISSION_PLANNED: "TOGGLE_MISSION_PLANNED",
}

export default CampPageActionTypes
