const CampSheetActionTypes = {
  SET_CURRENT_CAMP_SHEET: "SET_CURRENT_CAMP_SHEET",
  FETCH_CAMP_SHEET_LIST_START: "FETCH_CAMP_SHEET_LIST_START",
  FETCH_CAMP_SHEET_LIST_SUCCESS: "FETCH_CAMP_SHEET_LIST_SUCCESS",
  FETCH_CAMP_SHEET_LIST_FAILURE: "FETCH_CAMP_SHEET_LIST_FAILURE",
}

export default CampSheetActionTypes
