const CampSheetActionTypes = {
  SET_CURRENT_CAMP_SHEET: "SET_CURRENT_CAMP_SHEET",
  FETCH_CAMP_SHEET_LIST_START: "FETCH_CAMP_SHEET_LIST_START",
  FETCH_CAMP_SHEET_LIST_SUCCESS: "FETCH_CAMP_SHEET_LIST_SUCCESS",
  FETCH_CAMP_SHEET_LIST_FAILURE: "FETCH_CAMP_SHEET_LIST_FAILURE",
  FETCH_CURRENT_CAMP_SHEET_BY_ID_START: "FETCH_CURRENT_CAMP_SHEET_BY_ID_START",
  FETCH_CURRENT_CAMP_SHEET_BY_ID_SUCCESS: "FETCH_CURRENT_CAMP_SHEET_BY_ID_SUCCESS",
  FETCH_CURRENT_CAMP_SHEET_BY_ID_FAILURE_NONE_FOUND:
    "FETCH_CURRENT_CAMP_SHEET_BY_ID_FAILURE_NONE_FOUND",
  FETCH_CURRENT_CAMP_SHEET_BY_ID_FAILURE_NO_PERMISSION:
    "FETCH_CURRENT_CAMP_SHEET_BY_ID_FAILURE_NO_PERMISSION",
  FETCH_CHAR_SHEETS_OF_PLAYERS_FAILURE: "FETCH_CHAR_SHEETS_OF_PLAYERS_FAILURE",
}

export default CampSheetActionTypes
