const CampSheetActionTypes = {
  FETCH_CURRENT_CAMP_SHEET_START: "FETCH_CURRENT_CAMP_SHEET_START",
  FETCH_CURRENT_CAMP_SHEET_SUCCESS: "FETCH_CURRENT_CAMP_SHEET_SUCCESS",
  FETCH_CURRENT_CAMP_SHEET_FAILURE_NONE_FOUND: "FETCH_CURRENT_CAMP_SHEET_FAILURE_NONE_FOUND",
  FETCH_CURRENT_CAMP_SHEET_FAILURE_NO_PERMISSION: "FETCH_CURRENT_CAMP_SHEET_FAILURE_NO_PERMISSION",
  FETCH_CHAR_SHEETS_OF_PLAYERS_FAILURE: "FETCH_CHAR_SHEETS_OF_PLAYERS_FAILURE",
}

export default CampSheetActionTypes
