const UserActionTypes = {
  FETCH_CURRENT_USER_START: "FETCH_CURRENT_USER_START",
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILURE: "FETCH_CURRENT_USER_FAILURE",
}

export default UserActionTypes
