const AppActionTypes = {
  TOGGLE_POPUP: "TOGGLE_POPUP",
  TOGGLE_POPUP_FOR_EDIT: "TOGGLE_POPUP_FOR_EDIT",
  ADD_FLASH_MESSAGE: "ADD_FLASH_MESSAGE",
  FETCH_WEAPONS: "FETCH_WEAPONS",
  FETCH_WEARABLES: "FETCH_WEARABLES",
  FETCH_ITEMS: "FETCH_ITEMS",
  FETCH_RACES: "FETCH_RACES",
  FETCH_CLASSES: "FETCH_CLASSES",
  FETCH_ADDITIONAL_RESOURCES_FAILURE: "FETCH_ADDITIONAL_RESOURCES_FAILURE",
}

export default AppActionTypes
