const AppActionTypes = {
  TOGGLE_POPUP: "TOGGLE_POPUP",
  TOGGLE_POPUP_FOR_EDIT: "TOGGLE_POPUP_FOR_EDIT",
  ADD_FLASH_MESSAGE: "ADD_FLASH_MESSAGE",
  FETCH_ADDITIONAL_RESOURCES_START: "FETCH_ADDITIONAL_RESOURCES_START",
  FETCH_ADDITIONAL_RESOURCES_SUCCESS: "FETCH_ADDITIONAL_RESOURCES_SUCCESS",
  FETCH_ADDITIONAL_RESOURCES_FAILURE: "FETCH_ADDITIONAL_RESOURCES_FAILURE",
}

export default AppActionTypes
