const CharPageActionTypes = {
  MAKE_A_CHECK: "MAKE_A_CHECK",
  EQUIP_WEAPON: "EQUIP_WEAPON",
  EQUIP_ITEM: "EQUIP_ITEM",
  EQUIP_WEARABLE: "EQUIP_WEARABLE",
  UNEQUIP_WEAPON: "UNEQUIP_WEAPON",
  UNEQUIP_ITEM: "UNEQUIP_ITEM",
  UNEQUIP_WEARABLE: "UNEQUIP_WEARABLE",
}

export default CharPageActionTypes
