const CharSheetActionTypes = {
  SET_CURRENT_CHAR_SHEET: "SET_CURRENT_CHAR_SHEET",
  FETCH_CHAR_SHEET_LIST_START: "FETCH_CHAR_SHEET_LIST_START",
  FETCH_CHAR_SHEET_LIST_SUCCESS: "FETCH_CHAR_SHEET_LIST_SUCCESS",
  FETCH_CHAR_SHEET_LIST_FAILURE: "FETCH_CHAR_SHEET_LIST_FAILURE",
}

export default CharSheetActionTypes
