const CharSheetActionTypes = {
  FETCH_CHAR_SHEET_LIST_START: "FETCH_CHAR_SHEET_LIST_START",
  FETCH_CHAR_SHEET_LIST_SUCCESS: "FETCH_CHAR_SHEET_LIST_SUCCESS",
  FETCH_CHAR_SHEET_LIST_FAILURE: "FETCH_CHAR_SHEET_LIST_FAILURE",
  FETCH_CURRENT_CHAR_SHEET_BY_ID_START: "FETCH_CURRENT_CHAR_SHEET_BY_ID_START",
  FETCH_CURRENT_CHAR_SHEET_BY_ID_SUCCESS: "FETCH_CURRENT_CHAR_SHEET_BY_ID_SUCCESS",
  FETCH_CURRENT_CHAR_SHEET_BY_ID_FAILURE_NONE_FOUND:
    "FETCH_CURRENT_CHAR_SHEET_BY_ID_FAILURE_NONE_FOUND",
  FETCH_CURRENT_CHAR_SHEET_BY_ID_FAILURE_NO_PERMISSION:
    "FETCH_CURRENT_CHAR_SHEET_BY_ID_FAILURE_NO_PERMISSION",
  FETCH_ADDITIONAL_CHAR_SHEET_RESOURCES_FAILURE: "FETCH_ADDITIONAL_CHAR_SHEET_RESOURCES_FAILURE",
  FETCH_CHAR_SHEET_RACE_SUCCESS: "FETCH_CHAR_SHEET_RACE_SUCCESS",
  FETCH_CHAR_SHEET_CLASS_SUCCESS: "FETCH_CHAR_SHEET_CLASS_SUCCESS",
  FETCH_CHAR_SHEET_CAMPAIGN_SUCCESS: "FETCH_CHAR_SHEET_CAMPAIGN_SUCCESS",
}

export default CharSheetActionTypes
