const CharSheetActionTypes = {
  FETCH_CHAR_SHEET_LIST_START: "FETCH_CHAR_SHEET_LIST_START",
  FETCH_CHAR_SHEET_LIST_SUCCESS: "FETCH_CHAR_SHEET_LIST_SUCCESS",
  FETCH_CHAR_SHEET_LIST_FAILURE: "FETCH_CHAR_SHEET_LIST_FAILURE",
  SET_CURRENT_CHAR_SHEET_ID: "SET_CURRENT_CHAR_SHEET_ID",
  FETCH_CURRENT_CHAR_SHEET_START: "FETCH_CURRENT_CHAR_SHEET_START",
  FETCH_CURRENT_CHAR_SHEET_SUCCESS: "FETCH_CURRENT_CHAR_SHEET_SUCCESS",
  FETCH_CURRENT_CHAR_SHEET_FAILURE: "FETCH_CURRENT_CHAR_SHEET_FAILURE",
}

export default CharSheetActionTypes
